baseURL = 'https://sp00kyb00k.pages.dev'
languageCode = 'en-us'
title = 'Sp00kyB00k - A gh@stly bl0g'
theme = 'ananke'

DefaultContentLanguage = "en"
Paginate = 10
enableRobotsTXT = true

[params]
author = "Sp00kyB00k"
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-purple"
body_classes = 'baskerville bg-grey'
post_content_classes = 'athelas'
recent_posts_number = 3

[picture]
featured_image_class = 'cover bg-top'
